default_config:

homeassistant:
  name: Casa Yarumo (demo)
  time_zone: America/Bogota
  unit_system: metric
  currency: COP
  country: CO
  packages: !include_dir_named packages

automation: !include automations.yaml   # aquí escribe Savi sus automatizaciones aprobadas
script: !include scripts.yaml

recorder:
  purge_keep_days: 30
  exclude:
    entity_globs:
      - sensor.*_potencia      # la potencia cambia mucho; Savi la lee en vivo
